kind: pipeline
name: "Push drone"

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: build
    password: 57afbfc9-8f58-4be9-aba6-9111c32aa944
    repo: 314l0t/image6
    tags: {DRONE_COMMIT:0:7}
  trigger: 
  branch:
  - build/*
  - build
  event:
  - push


- name: build  
  image: latest
  settings:
    username: build
    password: 57afbfc9-8f58-4be9-aba6-9111c32aa944
    repo: 314l0t/image6
    tags: latest
  commands:
    - npm install 
    - run build 
  trigger: 
  branch:
  - master
  event:
  - push