kind: pipeline
name: "Push on non-master"

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: build
    password: 1234
    repo: build/app
    tags: latest
  commands:
    - yarn install 
    - go build

trigger: 
  branch:
  - build/*
  - build
  event:
  - push