kind: pipeline
name: "Push drone"

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: build
    password: 1234
    repo: build/app
    tags: {DRONE_COMMIT:0:7}
  trigger: 
  branch:
  - build/*
  - build
  event:
  - push

- name: build  
  image: latest
  settings:
    username: build
    password: 1234
    repo: build/app
    tags: latest
  commands:
    - npm install 
    - run build 
  trigger: 
  branch:
  - master
  event:
  - push