kind: pipeline
name: "Push drone"

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: 314l0t
    password: 57afbfc9-8f58-4be9-aba6-9111c32aa944
    repo: 314l0t/drone
    tags: ${DRONE_COMMIT:0:7}
  environment:
    SupabaseUrl:
      from_secret: supabase
    SupabaseAnonKey:
      from_secret: key
  trigger: 
  branch:
    exclude:
      - master
  event:
  - push

- name: build  
  image: latest
  settings:
    username: 314l0t
    password: 57afbfc9-8f58-4be9-aba6-9111c32aa944
    repo: 314l0t/drone
    tags: latest
  commands:
    - npm install 
    - npm run build 
  trigger: 
  branch:
    - master
  event:
  - push